### ISSUE TITLE
Open build directory crash

### ISSUE THREAD

**Issue by KjetilSvends** [PoESkillTree/PoESkillTree#540]
https://i.imgur.com/mUJx271.png

2019-12-11 09:06:55.8900|1|PoESkillTree.Views.App|Unhandled exception
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at PoESkillTree.ViewModels.Builds.BuildsControlViewModel.<.ctor>b__102_12() in C:\GitHub\PoESkillTree_Source\WPFSKillTree\ViewModels\Builds\BuildsControlViewModel.cs:line 269
   at PoESkillTree.Common.ViewModels.RelayCommand.Execute(Object parameter) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\Common\ViewModels\RelayCommand.cs:line 27
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2019-12-11 09:17:47.1095|1|PoESkillTree.Views.App|Unhandled exception
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at PoESkillTree.ViewModels.Builds.BuildsControlViewModel.<.ctor>b__102_12() in C:\GitHub\PoESkillTree_Source\WPFSKillTree\ViewModels\Builds\BuildsControlViewModel.cs:line 269
   at PoESkillTree.Common.ViewModels.RelayCommand.Execute(Object parameter) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\Common\ViewModels\RelayCommand.cs:line 27
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by EmmittJ** [comment]
It appears you might have two programs open trying use the same folder? Try closing one? You might also need to temporarily change the build directory

**Comment by KjetilSvends** [comment]
Do not think I have 2 programs accessing that save folder no.

I did change build folder, but it still crashes on old folder.

Did some testing, saving builds works fine to new build folder, it does however still crash when using 'Open build directory'.

Also tried renaming the default 'Builds' folder, it still crashes:

2019-12-11 15:11:09.4539|1|PoESkillTree.Views.App|Unhandled exception
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at PoESkillTree.ViewModels.Builds.BuildsControlViewModel.<.ctor>b__102_12() in C:\GitHub\PoESkillTree_Source\WPFSKillTree\ViewModels\Builds\BuildsControlViewModel.cs:line 269
   at PoESkillTree.Common.ViewModels.RelayCommand.Execute(Object parameter) in C:\GitHub\PoESkillTree_Source\WPFSKillTree\Common\ViewModels\RelayCommand.cs:line 27
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by EmmittJ** [comment]
Hmm, I would try restarting your computer? There might be something stuck using the build folder. It might be the File Explorer or something

**Comment by KjetilSvends** [comment]
I can do that, however it is the first time I've installed this program.

**Comment by EmmittJ** [comment]
Alrigh, I am not really sure what else to have you try. The error you are getting is a windows error that access to that folder have been denied. You might try running as admin if the restart doesn't end up working?

**Comment by EmmittJ** [comment]
You also might need to change the build folder to somewhere like "My Documents'

**Comment by EmmittJ** [comment]
You also might need to change the build folder to somewhere like "My Documents'

**Comment by brather1ng** [comment]
I can actually reproduce this. Seems like something changed here in .NET Core. According to https://stackoverflow.com/questions/35031856/access-is-denied-exception-when-using-process-start-to-open-folder, our current call to Process.Start isn't the recommended way for opening folders anyway (rather, the two argument one should be used with explorer.exe as the first argument).
