### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by Wires77** [PoESkillTree/PoESkillTree#573]
Here is the gist of the crash log:

```
2022-02-18 17:10:57.6330|1|PoESkillTree.Views.App|Unhandled exception
System.IO.IOException: Cannot create a file when that file already exists.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at PoESkillTree.SkillTreeFiles.SkillTree.CreateAsync(IPersistentData persistentData, ProgressDialogController controller, AssetLoader assetLoader) in D:\GitHub\PoESkillTree\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 546
   at PoESkillTree.Views.MainWindow.CreateSkillTreeAsync(ProgressDialogController controller, AssetLoader assetLoader) in D:\GitHub\PoESkillTree\WPFSKillTree\Views\MainWindow.xaml.cs:line 162
   at PoESkillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in D:\GitHub\PoESkillTree\WPFSKillTree\Views\MainWindow.xaml.cs:line 512
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I didn't get a screenshot when it happened the first time, but after rebooting it, it crashed again with the same error:
![image](https://user-images.githubusercontent.com/1209372/154773447-0488bb62-1d3d-4bca-827c-f1c66697096d.png)

This was after updating from at least since Conquerors of the Atlas.  Not sure when I last updated

**Comment by EmmittJ** [comment]
Can you look in `%appdata%\PoESkillTree - Conquerors of the Atlas\Data` and see if you have an `Opts.txt`? If you do, you can delete that and hopefully that will resolve the issue

**Comment by Wires77** [comment]
I didn't have that file, unfortunately.  Is `D:\GitHub` concerning at all?  I don't have that drive mounted...

**Comment by EmmittJ** [comment]
> I didn't have that file, unfortunately. Is `D:\GitHub` concerning at all? I don't have that drive mounted...
No, this is where I compile the source, so you are getting my stack trace dump. The important bit is: `WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 546` which I have fixed in the latest release.
